name: Secrets

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
      - name: Upload Findings
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-findings
          path: trufflehog.json